repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout with keep-output
        entry: |
          python -m nbstripout --keep-output $@
        language: system
        files: \.ipynb$
